Update dateTime and its option code
jkwchunjae/TableViewer.Blazor pull request #22
Opened 2024-07-03 08:08 UTC by ariaskkh

- `TvDateTimeOption`에 `RelativeTime`, `Format`을 추가하여 client가 변경할 수 있도록 구현
  - 특정 property에 대해 적용 불가
  - `Moment.net` library 추가 및 사용
-  `ToLocalTime()`을 사용하여 로직 단순화
- option에 따른 변경 로직을 DateTime 컴포넌트에서 `DateTimeService`로 이관
- `TvDateTimeOption`으로부터 `TvDateTimeGlobalOption`을 분리
  - `TvDateTimeOption`은 client로 부터 필요한 Option을 받을 때 사용
  - `TvDateTimeGlobalOption`은 provider로부터 받는 option data 저장

2024-07-04 00:44 UTC, jkwchunjae requested changes

2024-07-04 00:44 UTC, jkwchunjae commented on src/TableViewerBlazor/Service/DateTimeService.cs
> +        dateTime = dateTime.ToLocalTime();
```var localDateTime = dateTime.ToLocalTime();```
되도록 기존 값 변경하지 않았으면 좋겠어요.

2024-07-04 00:44 UTC, jkwchunjae commented on src/TableViewerBlazor/Service/TableViewerExtensions.cs
> +        services.AddSingleton<DateTimeService>();
Scoped 로 해야 합니다. 사람들 마다 타임존이 다를테니까요.

2024-07-04 00:44 UTC, jkwchunjae commented on src/TableViewerBlazor/Service/DateTimeService.cs
> +    public static string ConvertDateTimeFormat(DateTime dateTime, TvDateTimeOption option)
굳이 service에 static함수를 넣을 필요 없어보여요.
TvDateTimeView 멤버로 만듭시다.

2024-07-04 00:44 UTC, jkwchunjae commented on src/TableViewerBlazor/Service/DateTimeService.cs
> +    public TvDateTimeGlobalOption? GlobalOption { get; set; }
globaloption을 안 쓰는 것 같은데, 유저의 로컬 타임존은 어떻게 처리하나요?

2024-07-04 05:02 UTC, ariaskkh commented on src/TableViewerBlazor/Service/DateTimeService.cs
> +    public static string ConvertDateTimeFormat(DateTime dateTime, TvDateTimeOption option)
변경했습니다.

2024-07-04 05:02 UTC, ariaskkh commented on src/TableViewerBlazor/Service/TableViewerExtensions.cs
> +        services.AddSingleton<DateTimeService>();
revert 하면서 다시 Scoped로 변경되었습니다.

2024-07-10 04:28 UTC, jkwchunjae approved these changes

2024-07-10 04:28 UTC, merged